### PR TITLE
Remove invalid $PnE output

### PR DESCRIPTION
**Pull request by zbjornson**
From the FCS3.1 spec:

> $PnE
> If the floating point data type is used (either $DATATYPE/F/ or $DATATYPE/D/), then all parameters shall be stored as linear with $PnE/0,0/.

and

> $DATATYPE
> Note that $PnE/0,0/ shall be used for all parameters if $DATATYPE/F/ is used.

The part of the spec that talks about invalid `$PnE` values is providing recommendations to file readers. Writers should just not make invalid files.

I made this a subclassed warning so it can easily be silenced by users, but could just make it silently ignored also.

### CODE REVIEW

**Comment by whitews** [comment]
Hi Zach,

Thanks for the PR, this does seem to be embarrassingly true. I'll have to look through some history to see if there is any reason this was allowed. I tend to be very careful about changes to the FlowIO library, can you try your changes with the FlowKit test suite (master branch, the dev is currently a WIP)? If not, I can get to it in a week or so.

Kind regards,
Scott

**Comment by zbjornson** [comment]
Hi Scott,

Thanks for the fast feedback.

Here's this commit run against both FlowKit's develop and master: https://github.com/primitybio/FlowIO/actions/runs/3119270575. Here's FlowIO@master passing for comparison: https://github.com/primitybio/FlowIO/actions/runs/3119108070. I added that test action in another commit here.

Some of the warnings are about `0.0,0.0`, which is probably okay to allow. Fixed in my last push.

The failing test is creating an invalid FCS file. The input is `/$DATATYPE/I/` with `$PnE != 0,0` values. The test uses `sample.export(source='orig')` but writes as `/$DATATYPE/F/`, whereas it should basically use `sample.export(source='raw')` to store linearized data. `export()` could raise an exception if `source='orig'` but the source's `$PnE != 0,0`.

(The spec guidance isn't perfect btw. There's a small subset of float files with non-`0,0` $PnE values that should actually be linearized, and another small subset with non-`0,0` that shouldn't. 😢)

Best,
Zach

**Comment by whitews** [comment]
An update for future reference prior to merging: The original idea was to allow FlowKit exports of modified FCS metadata without changing the event data. However, since FlowIO only supports writing float data, this results in potentially invalid FCS files. The correct thing to do is to fix the float export and at some point add FlowIO support for creating FCS files with an integer data type.

**Comment by zbjornson** [comment]
That makes sense. Considering how few current instruments use integers, and considering that no hardware truly has a resolution of 1 at the high end of the scale, normalizing to float is not bad until FCS3.2 is supported here (different dtype per column, primarily to compactly support contiguous ints exceeding float range). One potential exception is the TIME channel; e.g. the Novocyte is integer-format and records time in microseconds.

Anyway, there's no bug here if you're only using FlowIO with floats, so fine with me if you just want to close this without merging. Maybe it could warn though to catch the invalid file created by the FlowKit tests noted above.

**Pull request merged**
